# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        datasource:
          host: sandboxdb.interop.community
          username: system
          password: ENC(eu7PppbSk0mHHUZjmjzZxPeU8X9aCckJ)
      sandboxManagerApi:
        url: https://${SBMA_HOST:sandbox-api.interop.community}
        transactionPath: /analytics/transaction
    authorization:
      url: https://auth.interop.community
    messaging:
      pubsub:
        enabled: true
        forSandboxes: travisdstu2,PulmonaryEmbolismDSTU2,noman_dstu2,nomanstu3,nomandstu2,PulmonaryEmbolism2,PulmonaryEmbolismVer
        subscription:
          channel:
            endpoint: http://pubsub.interop.community:9002/fhir-subscription/publish
        includeSourceQueryParameter: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
