# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        datasource:
          host: ${DB_HOST:sandboxdb.interop.community}
          username: ${DB_USER:system}
          password: ${DB_PASSWORD:password}
        sandboxGateway:
          url: ${GATEWAY_HOST}
      sandboxManagerApi:
        url: ${SBMA_HOST:https://sandbox-api.interop.community}
        transactionPath: /analytics/transaction
    authorization:
      url: ${AUTH_HOST:https://auth.interop.community}
    messaging:
      pubsub:
        enabled: true
        forSandboxes: travisdstu2,PulmonaryEmbolismDSTU2,noman_dstu2,nomanstu3,nomandstu2,PulmonaryEmbolism2,PulmonaryEmbolismVer
        subscription:
          channel:
            endpoint: http://pubsub.interop.community:9002/fhir-subscription/publish
        includeSourceQueryParameter: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
